#在线时间在该时限内的玩家将被监控 (小时)
tyroHours: 10
#一次性存取物品监测列表, 达到阈值时预警 (名称:个数)
itemMap:
  GUNPOWDER: 12
  DIAMOND: 10
  IRON_INGOT: 64
#周期内破坏方块监测列表, 达到阈值时预警 (名称:个数)
brokenMap:
  COBBLESTONE: 10
#玩家破坏方块的监测周期 (分钟)
brokenCycle: 5

#周期内放置物品监测列表, 达到阈值时预警 (名称:个数)
placeMap:
  TNT: 5
#玩家放置物品的监测周期 (分钟)
placeCycle: 5

#周期内使用流体桶的监测列表, 填写桶类型和次数, 达到阈值时预警 (名称:次数)
liquidMap:
  LAVA_BUCKET:
    limit: 1
    height: 64
#玩家使用流体桶的监测周期 (分钟)
liquidCycle: 5
#岩浆桶判定范围. 0为关闭, 若开启此选项则会在以岩浆桶为中心, 定义值为半径
#的立方体内发现有可燃物时无视高度进行预警. 注意!若范围过大会造成极大的服务器负担
lavaBucketRange: 1

#周期内生火, 填写使用的工具(一般只有打火石)和次数, 达到阈值时预警 (名称:次数)
fireMap:
  FLINT_AND_STEEL: 1
#玩家使用生火工具的监测周期 (分钟)
fireCycle: 5

#受监测的实体列表, 玩家周期内杀死达到阈值的实体时预警 (名称:斩杀数)
entityMap:
  PLAYER: 1
#统计实体死亡次数的周期 (分钟)
entityCycle: 5

# 检测tnt复制，玩家在粘液块及珊瑚或活塞旁放置tnt时预警
# true为开启，false为关闭
tntDupePredicate: true

#白名单尝试松弛周期 (分钟) 每隔一段时间尝试将游玩时限已达监测时限的玩家移除白名单
whiteCycle: 60

#启用日志, 日志文件在配置文件中, 多个日志会自动重命名不会覆盖, 其中包含调试信息
debug: false
