name: TyroDetector
version: ${version}
main: org.gbcraft.tyrodetector.TyroDetector
authors: [IceBlues7]
description: Detect tiro action
api-version: 1.13

commands:
  tyro:
    description: The tyro detector default command.
    permission: tyro.base
