name: TyroDetector
version: ${version}
main: org.gbcraft.tyrodetector.TyroDetector
authors: [IceBlues7]
depend: [Plan]
description: Detect tiro action

commands:
  tyro:
    description: The tyro detector default command.
    permission: tyro.base
